* 新冠                                                                 :新冠:

** 人类需要自我革命                                                    :环境:

   人与自然是辩证统一的关系.

   1. _自然界_ 是 _人类社会_ 形成的 _前提_.

   2. _实践_ 是分化 _自然界_ 和 _人类社会_ 的前提, 也是统一 _自然界_ 和 _人类社会_ 的基础.

   3. 人类可以在 _认识自然规律_ 的基础上, 发挥 _主观能动性_ 改造自然.

   启示: 人类需要自我革命, 要保持人类与自然和谐统一.

** 中特是抵御风险的保证                                                :中特:

   衡量国家的制度: 在风险时的应对.

   疫情中: 组织能力, 执行能力, 彰显 _集中力量办大事_ 的优势, 和中特的优越性.

   中特: {政治, 经济, 文化, 治理, 体制, 以人为本, 党对军队绝对领导, 国际主义} 优势.

   抗疫: 证明中特优越性, 是抵御风险的重要保证.

** 人民抗疫启示                                                        :中特:

   国人: 不屈的意志, 苦难考验了国人, 也锻炼了国人.

   近代: 国人的意志, 克服苦难.

   古代: 国人生命力, 忍耐力, 创造力, 为是国人自豪.

   启示: 只要激发国人意志, 就创造辉煌.

** 如何 "弘扬抗疫精神, 实现民族复兴"                                   :道德:

   疫情中: _生命至上_, _举国同心_, _尊重科学_ 的伟大抗疫精神.

   弘扬精神, 要:

   1. 坚持党的领导: 党是国人的主心骨.

   2. 推进治理体系现代化: 疫情是对我国的考验.

   3. 用于斗争: 面对矛盾迎难而上, 解决重大矛盾, 夺取新时代斗争胜利.

** 不是最后一次危机, 对全球挑战的启示                                  :当代:

   _疫情_ 和 _百年未有变局_ 相互影响, 但 _和平_ 与 _发展_ 的主题不变.

   各国人民期待 _和平发展_, _合作共赢_.

   启示:

   1. 各国 _互联互通_, _休戚与共_, 应有 _命运共同体_ 意识, 合作共赢, 抛弃 _意识形态_ 争论.

   2. _经济全球化(世贸)_ 是现实和历史潮流, 维护多边主义, 反对单边主义.

   3. 人类需要自我革命, 生态文明.

   4. _全球治理体系(联合国)_ 需要改善, 坚持多边主义, 各国平等, 合作共赢.

* 物质世界辩证                                                         :马原:

** 矛盾的 _同一性_ 和 _斗争性_

   坏事变好事, 物极必反.

   _同一性_ 和 _斗争性_ 是 _矛盾_ 的两种基本属性.

   1. 概念

      1) 同一性: 双方相互依存, 相互贯通的趋势

      2) 斗争性: 双方相互排斥, 相互分离的趋势.

   2. 辩证关系: 两者相互制约, 没有斗争性就没有同一性.

** 矛盾的 _普遍性_ 和 _特殊性_

   具体问题具体分析, 马克思主义中国化, 事物不同发展阶段有不同特征.

   1. 概念

      1) 普遍性(共性): 事物发展始终存在矛盾, 无处不在, 无时不有.

      2) 特殊性(特性): 具体事物具体矛盾各有特点.

   2. 辩证关系: 共性是无条件的, 绝对的. 特性是有条件的, 相对的. 事物都是共性和特性的统一体.

** 新冠危机与机遇                                                      :新冠:

   人生机遇, 中华民族复兴机遇.

   疫情的危机下蕴藏机遇, 体现辩证思想, 它们必然在一定的条件下相互转化.

   1. 用全面, 辩证的眼光看待问题, 善于化不利为有利.

   2. 培养辩证思维, 要 {承认, 分析, 解决} 矛盾, 还要洞察事物发展规律.

   3. 客观地, 发展地, 全面地, 系统地, 联系地观察事物, {分析, 解决} 问题.

* 客观规律性与主观能动性

** 主观能动性与客观规律性                                              :马原:

   改造世界, 把握规律, 困境破局.

   1. _意识_ 是 _物质_ 的产物, 是 _客观世界_ 在人脑中的 _主观映象_, 对 _客观世界_ 由能动的作用.

      1) 主体的实践和认识活动具有 {自觉, 目的, 计划, 创造} 性.

      2) 主体不仅能认识事物的现象, 还能认识事物的本质和规律.

      3) 主体由 _意识_ 指导改造 _客观世界_.

      4) _意识_ 调控人的 _行为_ 和 _生理活动_.

   2. 正确理解主观能动性和客观规律性的关系.

      1) 从实际出发, 把握事物发展规律.

      2) _实践_ 是发挥主观能动性的基本途径.

      3) 主观能动性依赖一定物质条件.

** 历史必然性与人的选择性                                              :近代:

   社会形态更替的客观必然性: 社会形态依次更替的规律是客观的.

   人的选择性: 社会主体有目的地选择的创造性活动.

   社会规律制约人, 人有能动性和选择性.

   取决于民族利益, 交往, 和对历史必然性和民族特点的把握程度.

* 认识世界与改造世界                                                   :马原:

** 认识来源于实践

   1. 实践是认识的来源.

   2. 实践是认识发展的动力: 实践的需要推动认识发展.

   3. 实践是认识的目的: 不是为认识而认识, 认识的目的是为了实践.

   4. 实践是检验真理的唯一标准.

** 理性因素与非理性因素

   1. 理性因素: 理性直观, 理性思维能力. {指导, 解释, 预见} 作用.

   2. 非理性因素: 情感, 意志, 欲望等. {激活, 驱动, 控制} 作用.

   马原即肯定理性因素主导, 又承认非理性因素作用.

** 真理与谬误

   对的变成错的, 错的变成对的.

   1. 概念

      1) 真理: {客观, 绝对, 相对} 性, _正确认识_ 会促进 _实践_ 成功.

      2) 谬误: 相反.

   2. 辩证关系: 真理与谬误 _对立统一_, 在一定条件下相互转化.

** 真理与价值

   遵循科学创造价值, 违背科学自尝恶果.

   真理: 制约实践的客观尺度, 实践的目标之一.

   价值: 实践的根本目标, 制约实践的主体尺度.

   真理和价值辩证统一.

   实践中坚持 {科学, 人文} 精神, 科学: 理性思维, 符合逻辑, 人文: 以人为本.

* 双循环                                                               :当代:

** 双循环背景

   党对 _百年未有大变局_, _经济向高质量发展_ 中出现的矛盾, 做出的强国战略.

   国内形势: 经济向高质量发展, 改变发展模式是 dssq.

   国际形势: 百年未有大变局, 疫情肆虐, 经济低迷, 保护主义抬头, 全球供应链大调整.

   党根据我国发展情况和国际形势变化, 主动战略选择.

** 是否停止开放

   误读.

   国内循环: 发挥内需潜力, 连通国内外市场, 推动可持续发展.

   改革开放以来, 中国融入全球产业链, 即使疫情弱化全球产业链, 中国仍依赖全球产业链.

   以国内循环为主体, 以 _扩大内需_ 为 _战略基点_, 扩大高水平开放.

** 为双循环提供动能

   1. 国内循环为主体: 发挥市场规模优势, 降低外部冲击的压力.

   2. 深化改革为基本途径: _供给侧结构性改革_.

   3. 扩大开放力度.

   4. 优势互补, 高质量发展的区域经济布局.

* 高质量发展                                                           :当代:

** 如何认识 "我国已进入高质量发展阶段"

   高速增长->高质量发展: 是划时代的事件, 理解 "我国..." 的内涵意义重大.

   1. 满足人民美好生活需要的发展.

   2. {高质量, 有效率, 公平, 可持续, 安全} 的发展.

   3. 体现新发展理念的发展.

   4. 以 _供给侧结构性改革_ 为 _主线_ 的发展.

   5. 建立在现代化经济体系基础上的发展.

** 如何做

   1. 重视促进高质量发展的因素, 构建双循环格局, 发挥经济潜力, 实现 {...} 的发展.

   2. 产业结构优化升级, 供给侧结构性改革, 乡村振兴, 制造业, 实体经济, 文化产业.

   3. 扩大内需为战略基点.

   4. 自主创新能力.

   5. 用于革新.

   6. 一带一路.

* 市场与政府                                                           :当代:

** {市场, 政府} 万能论是错误的

   经济体制改革的核心问题: 处理政府和市场的关系, 市场决定资源分配, 政府发挥作用.

   前提: 消除 {市场, 政府} 万能论, 协调市场和政府.

   市场: 资源配置最优化. 我国是 _社会主义市场经济体制_, 要发挥社会主义制度优越性, 发挥党和政府的积极作用.

   政府: 保持宏观经济稳定, 加强 {公共服务, 市场监管}, 维护秩序, 推动可持续发展, 实现共同富裕.

** 结合市场与政府

   1. 认识 _有效市场_ 和 _有为政府_ 的统一性: 二者有机统一, 相辅相成, 市场有效是政府的目的.

   2. 围绕政府与市场的统一推动改革, 坚持社会主义市场经济改革方向.

   3. 完善产权制度和要素市场化配置.

* 科技创新                                                             :当代:

** 创新的必要性和要求

   必要性: 发展动力决定发展效能, 坚持创新是应对环境变化, 把握主动权的关键.
   百年未有大变局, 国内外环境复杂, 创新决定发展, 决定未来.

   要求: 创新为国家发展的核心, 推动 {理论, 制度, 科技, 文化} 创新, 使创新成为社会风气.

** 怎么做

   1. {科教兴国, 人才强国, 创新驱动发展} 战略.

   2. 国家创新体系建设, 推动科技创新与经济社会发展融合.

   3. 企业为主体, 市场为导向, 产学研融合的创新体系.

   4. 基础研究战略科技, 推动重大科技创新.

   5. 创新文化, 知识产权保护.

   6. 积极有效的人才政策.

* 就业, 民生, 脫贫                                                     :当代:

** 为什么保市场主体就是保民生就业

   长远来看, 民生靠就业保障.

   市场主体是就业机会的提供者. 就业保民生的政策, 取决于市场主体的发展.

   民生 -> 就业 -> 市场主体.

** 六稳六保, 怎么做

   六稳: 就业, 金融, 外贸, 外资, 投资, 预期工作.

   六保: 就业, 民生, 市场主体, 粮食, 供应链, 基层运转.

   _就业_ 为首位.

   1. 就业: 就业优先政策, 增强企业创造就业岗的能力.

   2. 民生: 困难群体基本生活保障.

   3. 市场主体: 帮助中小企业度过难关.

   4. 粮食: 发挥 "三农" 作用.

   5. 供应链: 产业链协同复工复产, 保持稳定和竞争力.

   6. 基层: 提高财政资金使用率.

** 如何脫贫

   1. 精准脫贫.

   2. 坚决打赢脫贫攻坚战.

   3. 成功不会自己冒出来.

* 十四五 (全面小康) 和 2035 远景 (社现)                                :当代:

** 全面小康是新起点

   1. 全面小康是 _社现国家_ 的启动计划, 为全面建设 _社现国家_ 奠定起初.

   2. 实现 2035 远景必须立足十四五规划, 坚持全面深化改革, 扩大对外开放.

** 怎么做

   1. 党的领导.

   2. 社会主义政治建设.

   3. 保持港澳稳定.

   4. 两岸和平发展, 祖国统一.

   5. 营造良好外部环境.

   6. 健全规划制定和落实机制.

* 黄河生态保护                                                         :环境:

** 保护黄河事关民族伟大复兴

   生态文明关系人民福祉, 关系民族未来.

   黄河是生态屏障, 是重要经济地带, 也是脫贫重要地区.

   推动黄河流域高质量发展, 解决黄河流域诸多问题, 对社会稳定, 民族团结有重要意义.

   _社现_ 是人与自然和谐共生的现代化, 即要满足人民的物质精神需要, 又要满足生态环境需要.

** 怎么做

   1. 坚持人与自然和谐共生: 保护人与自然的生命共同体, 践行 _绿水青山就是金山银山_ 的理念.

   2. 实施主体功能战略区, 各地区因地制宜.

* 抗战                                                                 :近代:

** 近代反侵略战争失败的原因

   1. 社会制度腐败: 根本原因.

   2. 经济技术落后.

** 抗战是中华民族伟大复兴的转折点

   1. 粉碎日本帝国主义殖民中国的图谋, 维护国家主权和领土完整, 洗刷近代耻辱.

   2. 确立中国大国地位, 赢得世界尊敬.

   3. 坚定国人民追求独立的意志.

   4. 抗战精神永远激励国人.

** 抗战胜利原因

   1. 党发挥中流砥柱.

   2. 以爱国主义为核心的民族精神的胜利.

   3. 全民族奋勇抗战的胜利.

   4. 世界反法西斯同盟国并肩作战的胜利.

** 日本正确对待历史

    中日友好, 符合两国人民利益, 维护亚洲和平.

    正确对待历史, 是中日关系发展的基础.

    牢记历史, 珍爱和平.

* 抗美援朝                                                             :近代:

** 抗美援朝是帝国主义者主动的

   我国成立之处, 百废待兴, 急需巩固政权.

   国际, 以美为首的帝国主义国家封锁中国, 想要扼杀我国.

   朝鲜内战爆发, 美国武装干涉朝鲜, 还武装干涉台海.

** 抗美援朝是中华民族伟大复兴的里程碑

   1. 粉碎美国扼杀中国的图谋, 巩固新生政权.

   2. 奠定中国在亚洲和国际的地位.

   3. pla 取得经验, 促进国防现代化.

   4. 改变二战后亚洲格局.

** 抗美援朝精神

   要传承以 {爱国, 革命英雄, 乐观, 忠诚, 国际} 主义为中心的抗美援朝精神.

   抗美援朝精神是党和 pla 的精神写照, 也是中华民族精神的体现.

   抗美援朝精神激励国人克服困难.

* 党与中华民族伟大复兴                                                 :近代:

** 近代中国危机是什么

   封建统治者腐朽无能, 资本主义列强侵略, 中国沦为办殖民地办封建社会.

   为了救亡图存, 从戊戌变法到辛亥革命, 国人进行了不懈的探索, 但都失败了, 无法改变中华民族的命运.

** 党的领导地位

   党的初心是为人民某幸福, 为民族某复兴, 确定新民主主义的正确道路.

   党经过土地革命战争, 抗日战争, 解放战争, 推翻 _帝国主义_, _封建主义_, _官僚资本主义_.

   我国成立后, 党通过抗美援朝战争稳定政权, 从 _新民主主义社会_ 过渡到 _社会主义社会_.

   党十一届三中全会后, 纠正 _文革_ 错误, 以经济建设为中心,
   坚持四项基本原则, 坚持改革开放, 坚持中特, 提高国力和人民生活水平.

   党十八大后, 进入中特新时代, 推进五位一体总布局, 四个全面战略布局, 彰显中特制度优势.

   事实表明, 坚持党的领导, 是历史发展的必然, 是人民的选择.

* 抗疫精神与人生价值                                              :新冠:道德:

** 抗疫精神与中华民族精神

   抗疫精神: 生命至上, 舍生忘死, 举国同心, 尊重科学, 命运与共.

   生命至上: 国人的仁爱传统.

   舍生忘死: 国人的顽强意志.

   举国同心: 国人的万众一心的团结.

   尊重科学: 国人的求真务实.

   命运与共: 国人的爱好和平.

   抗疫精神, 根植于中华民族的传统文化, 发扬民族精神, 传承了 {爱国, 集体, 社会} 主义精神.

** 在奉献中实现人生价值

   人生价值: 实践对于社会和个人所具有的价值, 包括社会价值和自我价值.

   社会价值: 实践对社会的价值.

   自我价值: 实践对个人生存和发展的价值.

   辩证关系:

   自我价值是人存在的必要条件, 是实现社会价值的前提.

   社会价值是社会存在的必要条件, 是实现自我价值的保障.

   评价:

   实践是否符合社会发展规律, 是否促进历史进步.

   服务人民, 奉献社会的高尚追求, 为人民服务.

* 民法典                                                               :道德:

** 经济社会发展是民法典的前提

   法律由一定的社会物质生活条件决定, 法律作为上层社会的主要成分, 产生于特定物质条件基础之上.

   社会物质生活条件: 与生存相关的 _物质资料生产方式_, 自然地理环境和人口等因素.

   物质资料生产方式决定法律本质, 生产力发展水平制约法律发展程度.

** 法律与道德

   法律与道德紧密联系, 相互促进.

   道德是法律的价值基础.

   法律为道德提供制度保障.

   道德融入法律体系, 使法律有道德导向, 有利于维护社会公平正义, 引导国人遵守家庭责任, 社会责任.

** 法制思维, 如何维护法律权威

   法制思维: 以法制价值为导向, 运用法律原则, 处理问题的思维模式.
   包括法律至上, 权利制约, 公平正义, 人权保障, 正当程序等.

   要做到: 学习法律知识, 掌握法律方法, 养成守法习惯, 守住法律底线.

   法律权威: 法律在社会生活中的 {作用, 影响, 公信} 力.

   要做到: 信仰法律, 遵守法律, 服从法律, 维护法律.

* 道德                                                                 :道德:

** 个人道德

   1. 提高个人道德修养的自觉性.

   2. 有效的道德修养方法: 思学并重, 知行合一等.

   3. 学习道德模范.

   4. 参与社会实践.

** 网络秩序

   公共生活需要公共秩序: 网络生活是生活的一部分 -> 网络生活是公共生活的一部分 -> 网络生活需要秩序.

   网络秩序要法律与道德共同维护.

   要正确使用网络工具, 正确引导网络舆论, 坚持权利与义务统一, 不损害国家和社会利益.

* 多边主义                                                             :当代:

** 联合国是和平发展的保障

   联合国宪章: 主权平等, 不干涉内政, 和平解决争端, 不使用武力, 履行国际义务.

   联合国宪章是普遍接受的国际关系准则.

   联合国宪章体现了人民渴望和平, 平等, 合作, 繁荣的愿望.

   挑战: 当前国际形势复杂, 某国家破坏秩序.

   联合国是多边主义的平台, 是维护和平稳定的基石.

   维护联合国是推动人类社会进步的根本.

** 联合国应该如何发挥作用

   1. 主持公道.

   2. 厉行法制.

   3. 促进合作.

   4. 聚焦行动.

** 多边主义

   时代主题: 和平, 发展.

   一方面, 世界多极化, 发展中国家和中国崛起.

   另一方面, {霸权, 保护, 单边} 主义.

   要:

   1. 合作共赢, 反对单边主义.

   2. 维护联合国.

   3. 公平正义, 反对贸易保护主义.

** 美国立场

   美国优先, 遏制中国崛起, 建立美国主导的世界秩序, 成为世界霸主.

   美国的行为: 是霸权主义, 强权政治的表现, 是对世界和平的威胁.

   美国破坏多边贸易规则和国际秩序, 破坏了全球贸易关系, 阻碍全球经济复苏.

* 开放                                                                 :当代:

** 国际竞争发展趋势

   百年未有大变局, 经济逆全球化, 保护主义, 单边主义, 经济低迷.

   同时, 新一轮科技革命, 当代综合国力竞争为创新力竞争.

** 如何做

   1. 营造开放包容的合作环境.

   2. 顺应数字化, 网络化, 智能化发展趋势, 推动服务贸易数字化.

   3. 开创互利共赢的合作局面.

** 共同开放, 开放型世界经济

   推进合作共赢: 命运共同体, 团结合作是必然选择, 推动经济全球化更开放包容, 平衡共赢.

   推进合作共担: 各国应同舟共济面对风险, 共同开放, 共担责任.

   推进合作共治: 多边主义, 维护世贸组织.

** 我国如何做

   1. 推动全面开放, 一带一路, 坚持引进来, 走出去.

   2. 建设高水平开放型经济新体制.

   3. 反对保护主义.

   习: 1. 扩大外资市场准入, 2. 知识产权国际合作, 3. 扩大商品和服务进口, 4. 国际宏观经济政策协调, 5. 对外开放政策落实.

* 新冠                                                                 :新冠:

** 我国贡献

   我国和平发展, 共同发展, 不称霸, 不扩张, 加快世界经济复苏.

** 我国对国际事物的态度

   中国需要世界, 世界需要中国.

   我国独立自主的和平外交政策, 和平发展, 人类命运共同体.

   我国是全球化发展的贡献者.

   我国是国际秩序的维护者.

** 习对世界抗疫的倡议

   是对我国抗疫的总结, 是世界抗疫的务实策略.

   蕴涵中华民族传统美德, 国人求真务实的精神, 国人的爱好和平.

   对国人负责, 也对世界负责.
