#+TITLE: 泛函分析

* 判断题

  1. [ ] 每一个距离空间都可以完备化
  2. [X] 任意个闭集的并为闭集
  3. [X] 任意个开集的交为开集
  4. [ ] 数列强收敛一定弱收敛
  5. [ ] $L^p[a,b]$ 为可分空间
  6. [X] $\ell^{\infty}$ 为可分空间
  7. [ ] Banch 空间是完备的
  8. [ ] 从赋范空间 $X \rightarrow X_1$ 的连续线性算子一定是有界线性算子
  9. [ ] 紧空间中任意闭子集是紧的

* 名词解释

  1. 距离空间

     设 $x$ 是任意非空集, 对 $\forall x, y \in x$, 有一实数 $d(x,y)$ 与之对应, 满足:

     1) 非负性: $d(x,y) \ge 0$, 且 $d(x,y) = 0$ 当且仅当 $x = y$

     2) 对称性: $d(y,x) = d(x,y)$

     3) 三角不等式: $d(x,y) \le d(x,z) + d(z,y)$

  2. 有穷交性质

     设 $\left\{ F_{\alpha} \right\}, \alpha \in I$ 是拓扑空间 $X$ 的闭集族, 如果族中任取有限个闭集,
     其交集不为空集, 则 $\bigcap\limits_{\alpha \in z}^{} F \ne \Phi$, 称 $\left\{ F_{\alpha} \right\}$ 有有穷交性质. 如果 $X$ 中
     任意闭集有有穷交性质, 称 $X$ 有有穷交性质.

  3. 列紧集

     $A$ 是距离空间 $X$ 的子集, 如果对 $A$ 中任意点列必有在 $X$ 中收敛子列,
     称 $A$ 为列紧集. 如果 $X$ 是列紧集, $X$ 成为列紧集空间.

  4. 赋范空间

     设 $X$ 是数域 $k$ (实数或复数) 上的线性空间, 函数 $\left| \left| \cdot \right| \right|: x \rightarrow R$ 满足条件:

     1) $\forall x \in X, \left| \left| x \right| \right| \ge 0$, 且 $\left| \left| x \right| \right| = 0$, 当且仅当 $x = 0$

     2) $\forall x \in X, \alpha \in k$, 有 $\left| \left| \alpha x \right| \right| = \left| \alpha \right| \left| \left| x \right| \right|$

     3) $\forall x, y \in X, \left| \left| x + y \right| \right| \le \left| \left| x \right| \right| + \left| \left| y \right| \right|$

     称 $\left| \left| \cdot \right| \right|$ 是 $X$ 上的一个范数, $X$ 上定义了范数 $\left| \left| \cdot \right| \right|$ 称为赋范空间.

  5. 线性算子

     设 $X, X_1$ 是赋范空间, $T$ 是 $X$ 中线性子空间 $D(T)$ 上到 $X_1$ 中的映射,
     满足条件: $\forall x, y \in D(T), \alpha \in K$, 有: $T(x+y) = Tx + Ty, T(\alpha x) = \alpha Tx$,
     称 $T$ 是 $X$ 到 $X_1$ 中的线性算子, 称 $D(T)$ 为 $T$ 定义域.

  6. Holder 不等式

     设 $E$ 是勒贝格可测集, $x(t), y(t)$ 为 $E$ 上的可测函数, 则有:
     $\int\limits_E^{} \left| x(t)y(t) \right| dt \le \left( \int\limits_E^{} \left| x(t) \right| ^p dt \right) ^{\frac{1}{p}} \cdot \left( \int\limits_E^{} \left| y(t) \right| ^q dt \right) ^{\frac{1}{q}}$, 其中 $p, q > 0$ 且 $\frac{1}{p} + \frac{1}{q} = 1$.

  7. Minkovski 不等式

     设 $E$ 是勒贝格可测集, $x(t), y(t)$ 为 $E$ 上的可测函数, $P \ge 1$, 有:
     $\left( \int\limits_E^{} \left| x(t) + y(t) \right| ^p dt \right) ^{\frac{1}{p}} \le \left( \int\limits_E^{} \left| x(t) \right| ^p dt \right) ^{\frac{1}{p}} + \left( \int\limits_E^{} \left| y(t) \right| ^p dt \right) ^{\frac{1}{p}}$

* 叙述

  1. Banach Steinhous 定理 (共鸣定理)

     设 $\left\{ T_{\alpha} \right\}, \alpha \in I$ 是 Banach 空间 $X$ 上的赋范空间 $X$ 到赋范空间 $X_1$ 中有界算子族.
     如果对 $\forall x \in X, \sup\limits_{\alpha \in I}^{} \left| \left| T_{\alpha} x \right| \right| < \infty$, 则 $\left\{ \left| \left| T_{\alpha} \right| \right| ^2 \right\}, (\alpha \in I)$ 是有界集.

  2. Hahn Banach 延拓定理

     设 $G$ 是赋范空间 $X$ 的子空间, $f$ 是 $G$ 上的有界线性泛函,
     则 $f$ 可保持范数不变 延拓到到全空间 $X$ 上,
     即存在 $X$ 上有界线性泛函 $F$:
     
     1) $\forall x \in G, F(x) = f(x)$

     2) $\left| \left| F \right| \right| = \left| \left| f \right| \right| _G$, 这里 $\left| \left| f \right| \right| _G$ 表示 $f$ 作为 $G$ 上有界线性泛函范数

  3. 举例说明同一集合上可同时定义不同的距离使其分别完备和不完备

     例: $C[a, b]$
     
     定义 $d_1(x_1(t), x_2(t)) = \max\limits_{a \le t \le b}^{} \left| x_1(t) - x_2(t) \right|$, 该距离下 $C[a, b]$ 完备.
     
     定义 $d_2(x_1(t), x_2(t)) = \int\limits_a^b \left| x_1(t) - x_2(t) \right| dt$, 该距离下 $C[a, b]$ 不完备.
